wifi_ssid: "wifi_ssid"
wifi_password: "wifi_password"
heatpump_ota_password: "heatpump_ota_password"
# if you want to manage from home assistant
# https://esphome.io/components/api.html?highlight=randomly%20generated
heatpump_encryption_key: "8S2Wl+av/oK3AyFETYQ0wLPm4AzQK97Z941h4OIcCXM=" 